[versions]
activity-compose = "1.8.2"
agp = "8.4.0-alpha13"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
compose-bom = "2024.01.00"
compose-compiler = "1.5.10"
coreKtx = "1.12.0"
datastore = '1.0.0'
espressoCore = "3.5.1"
firebase-bom = "32.7.4"
firebaseCrashlyticsPlugin = "2.9.9"
googleServicesPlugin = "4.4.1"
googleServicesWearable = "18.1.0"
hilt = "2.49"
hilt_androidx = '1.2.0'
horologist = '0.5.20'
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.22"
kspPlugin = "1.9.10-1.0.13"
ktlint = "0.46.1"
lifecycleRuntimeKtx = "2.7.0"
material = "1.11.0"
navigationCompose = "2.7.7"
play-services-ads = "23.0.0"
play-services-base = "18.3.0"
protobuf = "3.24.3"
protobufPlugin = "0.9.4"
splashscreen = "1.1.0-alpha02"
timber = "5.0.1"
wear-compose = "1.3.0"
wear-input = "1.2.0-alpha02"
wear-remote-interactions = '1.0.0'
wear-tiles = "1.0.1"
wear-watchface = "1.0.1"
wearToolingPreview = "1.0.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-iconscore = { module = "androidx.compose.material:material-icons-core" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt_androidx" }
horologist-composables = { group = "com.google.android.horologist", name = "horologist-composables", version.ref = "horologist" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3 = { group = "androidx.compose.material3", name = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "play-services-ads" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "play-services-base" }
playservices-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "googleServicesWearable" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wear-compose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wear-compose" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wear-input" }
wear-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wear-remote-interactions" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }