[versions]
activity-compose = "1.8.2"
agp = "8.2.2"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
compose-bom = "2024.02.02"
compose-compiler = "1.5.10"
datastore = '1.0.0'
firebase-bom = "32.7.4"
firebaseCrashlyticsPlugin = "2.9.9"
googleApiClient = "1.23.0"
googleApiDrive = "v3-rev20240123-2.0.0"
googleServicesPlugin = "4.4.1"
googleServicesWearable = "18.1.0"
hilt = "2.49"
hilt_androidx = '1.2.0'
horologist = '0.5.20'
kotlin = "1.9.22"
kspPlugin = "1.9.10-1.0.13"
ktlint = "0.46.1"
protobuf = '3.24.3'
protobufPlugin = "0.9.4"
splashscreen = "1.1.0-alpha02"
wear-compose = "1.3.0"
wear-input = "1.2.0-alpha02"
wear-remote-interactions = '1.0.0'
wear-tiles = "1.0.1"
wear-watchface = "1.0.1"
wearToolingPreview = "1.0.0"
credentials = "1.3.0-alpha01"
googleid = "1.1.0"
timber = "5.0.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material-iconscore = { module = "androidx.compose.material:material-icons-core" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

google-api-client = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClient" }
google-api-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiDrive" }

credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt_androidx" }
horologist-composables = { group = "com.google.android.horologist", name = "horologist-composables", version.ref = "horologist" }
playservices-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "googleServicesWearable" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wear-compose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wear-compose" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wear-input" }
wear-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wear-remote-interactions" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }